#!/bin/bash
mkdir -p /var/lib/lxc/android/rootfs/vendor
mkdir -p /var/lib/lxc/android/rootfs/dev
mkdir -p /var/lib/lxc/android/rootfs/data
mkdir -p /var/lib/lxc/android/rootfs/mnt
mkdir -p /var/lib/lxc/android/rootfs/proc
mkdir -p /var/lib/lxc/android/rootfs/tmp
mkdir -p /var/lib/lxc/android/rootfs/sys
mkdir -p /usr/lib/audiosystem-passthrough
mkdir -p /etc/phosh
mkdir -p /etc/systemd/system/bluetooth.service.d
mkdir -p /etc/systemd/user/pulseaudio.service.d
mkdir -p /etc/systemd/system/phosh.service.d
